CP = .:classes:/opt/pi4j/lib/'*':AllProjects/Pathfinder/src/main/java/

run :
	javac -classpath $(CP) AllProjects/Pathfinder/src/main/java/de/buschbaum/java/pathfinder/device/mpu6050/*.java      
	javac -classpath $(CP) AllProjects/Pathfinder/src/main/java/de/buschbaum/java/pathfinder/Main.java    
	sudo java -classpath $(CP) de.buschbaum.java.pathfinder.Main


